model:
  latent_dim: 256
  input_channels: 1
  input_height: 128
  input_width: 128

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
  beta: 1.0 # Weight for KLD loss
  device: "mps" # Default to MPS for Apple Silicon

data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
